version: 0.2
env:
  shell: bash
phases:
  pre_build:
    commands:
      - echo Logging in docker hub..
      - docker login --username shubhamagile --password Shubham@123
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build . -t shubhamagile/fastapi-fibonacci
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push shubhamagile/fastapi-fibonacci